version: "3.8"

services:


  ai:
    build:
      context: ai
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    volumes:
      - ./ai:/app

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "7000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - ai

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "1000:1000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend



networks:
  default:
    driver: bridge
