backend:
  base_url: "http://127.0.0.1:8000"
  endpoints:
    docs: "/docs"
    chat: "/chat"
    file: "/upload_file"
    chat_stream: "/chat"
  timeout: 240

app:
  app_title: "Dnd_helper"
  title: "D&D Helper"
  layout: wide
  default_temperature: 0.5
  default_model:
    - model: "gpt-4o-mini"
      provider: "openai"
  ai_models:
    - model: "gpt-4o-mini"
      provider: "openai"
    - model: "gemini-2.0-flash"
      provider: "google_genai"
  accepted_file_types:
    - "pdf"
    - "png"
    - "jpg"
    - "jpeg"
  settings_title: "Settings"
