backend:
  base_url: "http://127.0.0.1:8000"
  endpoints:
    docs: "/docs"
    chat: "/chat"
  timeout: 30

app:
  app_title: 'test_app_title'
  title: "AI Chatbot"
  layout: wide
  default_model: 'gemini-flash-2.0'
  ai_models:
    - gpt4
    - gemini-flash-2.0
  settings_title: 'Settings'
