backend:
  base_url: "http://127.0.0.1:8000"
  endpoints:
    docs: "/docs"
    chat: "/chat"
    file: "/upload_file"
  timeout: 30

app:
  app_title: "test_app_title"
  title: "AI Chatbot"
  layout: wide
  default_temperature: 0.5
  default_model:
    - model: "gemini-flash-2.0"
      provider: "google_genai"
  ai_models:
    - model: 'gpt-4o-mini'
      provider: 'openai'
    - model: 'gemini-flash-2.0'
      provider: 'google_genai'
  accepted_file_types:
    - "pdf"
    - "png"
    - "jpg"
    - "jpeg"
  settings_title: 'Settings'

